### ISSUE TITLE
centos：没有可用软件包 kernel-devel-5.18.1

### ISSUE THREAD

**Issue by mekkhalawang** [apernet/tcp-brutal#10]
几个centos都提示这个

**Comment by haruue** [comment]
CentOS Stream 9 官方软件仓库最新的内核版本是 5.14.0-419.el9 ， 其它版本的内核版本均为 4.x 或更低。 

如果你安装的是由第三方编译的内核， 请注意 headers 是随内核编译环境打包生成的， 官方仓库是不可能为第三方内核提供 headers 的， 你应该从下载内核包的网站寻找第三方内核的 headers 下载方式。

另请注意在 CentOS 7 上安装 tcp-brutal 是不太现实的， 请换用其它发行版。
