### ISSUE TITLE
  安装在PVE nat(debian 12)上出现:error: Cannot install 'linux-headers-6.1.0-10-cloud-amd64' 

### ISSUE THREAD

**Issue by ainp** [apernet/tcp-brutal#11]
Checking linux-headers ... not installed
Try to install linux-headers for 6.1.0-10-cloud-amd64 ...
Installing missing dependence 'linux-headers-6.1.0-10-cloud-amd64' with 'apt -y --no-install-recommends install' ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-6.1.0-10-cloud-amd64
E: Couldn't find any package by glob 'linux-headers-6.1.0-10-cloud-amd64'
bash <(curl -fsSL https://tcp.hy2.sh/): error: Cannot install 'linux-headers-6.1.0-10-cloud-amd64' with detected package manager, please install it manually.

**Comment by haruue** [comment]
之前没看到。 这里回复一下。

首先不建议在 Proxmox VE 母鸡上装这个。 一方面 hypervisor 应该追求极致的稳定性， 另一方面 vm 里面用不了 host 上装的内核模块（在哪个 vm 里跑 sing-box 就在哪个 vm 里装）。 在 host 上装的话只有直接跑在 host 上的程序和 containers 里跑的程序能用上。

此外， 虽然 PVE 基于 Debian， 但是 PVE 预装的内核和 Debian 是不一样的。 PVE 预装的内核版本号应当是以 `-pve` 结尾的， 然而你机器上识别出来的是 `6.1.0-10-cloud-amd64` 而不是 `6.1.0-10-pve`， 可能是因为你已经把内核换成了 Debian 内核了。 如果使用 PVE 预装的内核， 安装 headers 的正确方式是安装 `pve-headers` 这个包， 这样做会更新到最新的 PVE 内核并安装对应的 headers。

你看到的这个报错本身是因为 Debian 12 源当前没有 6.1.0-10 版本的 linux-headers， 你可以执行 `apt update && apt search 'linux-headers-6.1.0-.*-cloud-amd64'` 就能看到 Debian 12 源里当前只提供 6.1.0-11 到 6.1.0-17 版本的 linux-headers。 你需要先升级内核， 例如升级到 `6.1.0-17` ， 然后装上对应的 `linux-headers-6.1.0-17-cloud-amd64` 即可。

**Comment by yyiu** [comment]
```
apt install pve-headers-$(uname -r)
```
