### ISSUE TITLE
服务端已经安装并写上 TCP Brutal 的参数，客户端是 windows 或者 macOS 的话，需要写吗？

### ISSUE THREAD

**Issue by fscarmen** [apernet/tcp-brutal#13]
介绍最后的说道：客户端使用 TCP Brutal 可以获得更好的上传速度，但很多人使用的是 Windows, macOS 或手机，安装内核模块往往不现实。

请问即使是安装不了内核，但客户端仍然要写该参数才能使服务端生效还是不需要？

**Comment by tobyxdd** [comment]
需要
