### ISSUE TITLE
Installing missing dependence 'linux-headers-6.1.0-20-arm64'

### ISSUE THREAD

**Issue by ypxun** [apernet/tcp-brutal#17]
服务器是debian12，安装提示缺少这个依赖。我看了下issues里有个类似的问题，我就`apt search linux-headers-6.1.0-*-arm64`，搜索后没有20，20附近只有`linux-headers-6.1.0-18-arm64`和`linux-headers-6.1.0-21-arm64`，18和21分别安装成功后，还是安装失败，依赖只认20。
请问如果安装了21后，可以忽略这个20的依赖，正常使用吗？

**Comment by haruue** [comment]
linux-image 和 linux-headers 版本号需要一致。 如果缺少当前版本的 headers， 可以试试按照下面这个方法升级内核。 

1. 安装 `linux-image-6.1.0-21-arm64` 和 `linux-headers-6.1.0-21-arm64` （选 21 而不是 18， 因为引导程序通常默认启动最新的已安装内核）
2. 重启系统
3. 重新运行 tcp-brutal 安装脚本

**Comment by ypxun** [comment]
> linux-image 和 linux-headers 版本号需要一致。 如果缺少当前版本的 headers， 可以试试按照下面这个方法升级内核。
> 
> 1. 安装 `linux-image-6.1.0-21-arm64` 和 `linux-headers-6.1.0-21-arm64` （选 21 而不是 18， 因为引导程序通常默认启动最新的已安装内核）
> 2. 重启系统
> 3. 重新运行 tcp-brutal 安装脚本

谢谢，已成功。
