### ISSUE TITLE
安装时发生的问题

### ISSUE THREAD

**Issue by jzliming** [apernet/tcp-brutal#24]
bash <(curl -fsSL https://tcp.hy2.sh/)
用这个脚本，按装的时候，出现错误
![屏幕截图 2024-08-12 090304](https://github.com/user-attachments/assets/89e7f66a-ca3d-4593-a269-2e5083fb57d4)
Linux version 6.1.0-9-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)

**Comment by haruue** [comment]
镜像太老导致的， 和 #17 是同样的问题。

考虑到还有个 ssh 的洞， 建议直接升级系统

```
apt update
apt upgrade -y
reboot
```
