### ISSUE TITLE
vps的up,down设置的1000,客户端设置的up20,down150,是哪一个生效?

### ISSUE THREAD

**Issue by li12138** [apernet/tcp-brutal#25]
vps的up,down设置的1000,客户端gui for clash设置的up,20,down,150,是哪一个生效?

**Comment by haruue** [comment]
您好。 

按照您的描述， 是客户端配置的带宽（客户端上传 20 Mbps， 下载 150 Mbps）生效。

您可以参考文档里的这张流程图： https://hysteria.network/zh/docs/advanced/Full-Server-Config/#_6
