### ISSUE TITLE
安装脚本在 OpenWrt x86 软路由上运行不了

### ISSUE THREAD

**Issue by ghost** [apernet/tcp-brutal#27]
脚本在x86软路由上运行不了，有软路由能运行的脚本吗，软路由在这群体中可是主力

**Comment by haruue** [comment]
您好， 请问您提及的「软路由」是 OpenWrt 及其衍生系统吗？

OpenWrt 的话通过脚本安装应该不太现实。
不过， 或许我们能弄个 kmod 包， 可以在 OpenWrt 的 SDK 环境下编译的。

**Comment by ghost** [comment]
> 您好， 请问您提及的「软路由」是 OpenWrt 及其衍生系统吗？
> 
> OpenWrt 的话通过脚本安装应该不太现实。 不过， 或许我们能弄个 kmod 包， 可以在 OpenWrt 的 SDK 环境下编译的。

是openwrt, 现在科学上网这是主力，可惜我不会编译，希望能尽快出安装包，感谢

**Comment by haruue** [comment]
通常来说在服务端侧安装 tcp-brutal 加速下载就足够的。 你们服务端也用的 OpenWrt 吗？

**Comment by ghost** [comment]
> 通常来说在服务端侧安装 tcp-brutal 加速下载就足够的。 你们服务端也用的 OpenWrt 吗？

那不是，是希望在客户端安装能有更好的效果

**Comment by haruue** [comment]
简单弄了个教程。
https://github.com/haruue-net/openwrt-tcp-brutal

然而， 由于内核模块的版本严格绑定到内核， 并且 OpenWrt 无法单独更换内核， 提供能在任何 OpenWrt 上直接安装的 ipk 包是不现实的。

**Comment by kousyougi** [comment]
> 简单弄了个教程。 https://github.com/haruue-net/openwrt-tcp-brutal
> 
> 然而， 由于内核模块的版本严格绑定到内核， 并且 OpenWrt 无法单独更换内核， 提供能在任何 OpenWrt 上直接安装的 ipk 包是不现实的。

謝謝。按照這個教程。已經成功整合tcp-brutal到我的openwrt x86了。

請問 tcp-brutal可不可以整合到 https://github.com/ophub/amlogic-s9xxx-openwrt/ 的內核？
想把tcp-brutal功能加進s905x3的openwrt裡。

**Comment by haruue** [comment]
@kousyougi 

我现在没有相关的设备和测试环境， 我看了一下您提及的仓库， 你可以试试修改下面的文件：
1. 根据这个文件里的注释和示例添加 feeds： https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/config/openwrt-main/diy-part1.sh
2. 在这个文件里添加编译选项 `CONFIG_PACKAGE_kmod-brutal=y` ： https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/config/openwrt-main/config

我并没有进行相关测试， 如果您遇到问题， 请参考您提及的这个仓库的 [说明文档](https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/documents/README.cn.md) 或者给它 [提交 issue](https://github.com/ophub/amlogic-s9xxx-openwrt/issues/new/choose)。

**Comment by bslgw** [comment]
> 通常来说在服务端侧安装 tcp-brutal 加速下载就足够的。 你们服务端也用的 OpenWrt 吗？
openwrt必须安装。只有服务器安装，无效的

不安装会提示：failed to enable TCP Brutal at client: setsockopt IPPROTO_TCP TCP_CONGESTION brutal: no such file or directory: please make sure you have installed the tcp-brutal kernel module
