### ISSUE TITLE
无法使用 因为找不到linux-headers-5.4.0-189-generic

### ISSUE THREAD

**Issue by workmengxue** [apernet/tcp-brutal#28]
![image](https://github.com/user-attachments/assets/6ca3c3e4-9248-46ae-9c18-cc4c7fa185d9)

**Comment by workmengxue** [comment]
![image](https://github.com/user-attachments/assets/fc3d547a-b29a-4d46-8058-fc30f3fea150)

**Comment by haruue** [comment]
系统镜像太旧， 当前使用的内核的 kernel header 已经不在源中。

可尝试升级内核到源的最新版本， 通过以下命令
```bash
apt update
apt upgrade
reboot
```

此外， 5.4 内核仅支持在 IPv4 上使用 tcp-brutal， 通常是够用的（除非你的代理客户端通过 IPv6 连接到你的代理服务器）。
