### ISSUE TITLE
可以支持 alpine 吗

### ISSUE THREAD

**Issue by utccnu** [apernet/tcp-brutal#29]
安装了 linux-headers 后手动 make 也不成功

**Comment by haruue** [comment]
您好。

手动 make 不成功， 通常是因为已安装的内核版本和 linux-headers 版本不匹配所导致的。 这种情况下建议升级整个系统， 然后重启以使用新内核。

可能可以通过以下命令更新 Alpine 

```bash
apk update
apk upgrade
```

如果仍然不行， 请提供手动 `make && make load` 时的输出以获取更多帮助。

请注意， dkms / akms 只是调用 make 的工具， 在一个手动 make 会失败的环境中， 它们也没有魔法能够编译成功。

**Comment by haruue** [comment]
我安装了个 alpine 之后发现， 它默认用 lts 内核， 可以通过 uname -r 确认

```
test-alpine:~# uname -r
6.6.58-0-lts
```

这种情况下， 你需要安装的包并不是 `linux-headers` ， 而是 `linux-lts-dev` 。
此外， 你还需要安装 `alpine-sdk`， 它提供编译所需的工具， 比如编译器和 make。

我会在下面提供一个完整的安装步骤， 可以在 Alpine Linux 上安装 tcp-brutal。
请注意， Alpine Linux 是一个非常简陋的发行版， 它甚至没有 systemd。
除非你的 VPS 硬盘非常小， 否则请避免在物理机器上使用。

## 安装步骤

### 安装依赖

```bash
apk add linux-lts-dev alpine-sdk akms
```

### 下载源代码

```
git clone https://github.com/apernet/tcp-brutal /usr/src/tcp-brutal
```

### 创建 AKMBUILD 文件

将以下内容保存成 `/usr/src/tcp-brutal/AKMBUILD`

```bash
modname=brutal

_modsrcdir="/usr/src/tcp-brutal"
modver="$(git --git-dir="$_modsrcdir/.git" describe --tags --always)"

built_modules='brutal.ko'

build() {
  make ${MAKEFLAGS:-} -C "$kernel_srcdir" M="$builddir" src="$srcdir" modules
}
```

### 安装并载入

```
akms install all
modprobe brutal
```
