### ISSUE TITLE
tcp-brutal与udp-brutal

### ISSUE THREAD

**Issue by tomxiang1** [apernet/tcp-brutal#3]
个人使用感受，在同样的线路上跑tcp brutal没有udp brutal效果明显。tcp brutal速度不稳定也达不到设定速度。
个人觉得tcp brutal速度不稳定可能是受到tcp底层协议原理影响，tcp底层是顺序发包和顺序收包，一旦发生丢包就会阻塞重传。这样会不会是tcp brutal速度不稳定的主要原因。
能不能绕过TCP底层重传，打破TCP底层包顺序传输，是tcp brutal像udp brutal一样稳定的关键。
个人愚意，有不对的地方请指教。

**Comment by tobyxdd** [comment]
如果修改 TCP 协议本身就不再是 TCP 了，无法和标准实现兼容。不在这个项目考虑范围之内

**Comment by pendy99** [comment]
udp brutal是什么?有项目地址么?

> 个人使用感受，在同样的线路上跑tcp brutal没有udp brutal效果明显。tcp brutal速度不稳定也达不到设定速度。 个人觉得tcp brutal速度不稳定可能是受到tcp底层协议原理影响，tcp底层是顺序发包和顺序收包，一旦发生丢包就会阻塞重传。这样会不会是tcp brutal速度不稳定的主要原因。 能不能绕过TCP底层重传，打破TCP底层包顺序传输，是tcp brutal像udp brutal一样稳定的关键。 个人愚意，有不对的地方请指教。
