### ISSUE TITLE
时不时断连！

### ISSUE THREAD

**Issue by sxml** [apernet/tcp-brutal#8]
两个vps 之前部署其他没断过都有开xMux ,用XTLS_REALITY +TCP Brutal 时不时断连！要重新连接才能可以用。好像Mux 用h2mux就会断链

**Comment by tobyxdd** [comment]
这应该不是 TCP Brutal 的问题

**Comment by sxml** [comment]
> 这应该不是 TCP Brutal 的问题

电报搜索 看到别人也有同样情况 断链
